### ISSUE TITLE
Can this be retired?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stsci.imagestats#8]
@larrybradley , do you think by now there is enough functionality in Numpy, Scipy, or Astropy to completely replace `histogram1d` in this package? Seems ridiculous that we have to maintain this entire namespace package with only 1 function. If there is a replacement, what do you think about the performance in comparison? Please advise.

**Comment by larrybradley** [comment]
As far as I can tell, `histogram1d` simply computes a 1D histogram from a 2D array.  `numpy.histogram` can easily do this, just be sure to flatten the input array (e.g. `data.ravel()`).

**Comment by pllim** [comment]
cc @mcara

**Comment by mcara** [comment]
Personally, I do not understand what is bothering @pllim about this package. Just because a package was not updated for 4 years it does not mean it is useless: it is used throughout both HST data analysis tools (and probably calibration pipelines among which, [`acs_destripe()`](https://github.com/spacetelescope/acstools/blob/master/acstools/acs_destripe.py#L649) and JWST pipelines - confirm with @stsci-hack @philhodge @hbushouse 

Therefore, I do not understand something like this: _"Seems **ridiculous** that we have to maintain this **entire namespace package** with only 1 function."_ First of all, how much maintenance effort was spent on this entire package in the last, e.g., 4 years? Secondly, when you say _"package with only 1 function"_ do you mean `histogram1d`? That is not the _only_ (or main) function in this package - check out `src` directory as well as the `__init__.py` module ("main" module in this package). I know, I know... weird design decisions but it works.

In my opinion the effort to redesign existing software to switch to other packages will be a monumental effort at the very least by comparison to just "maintaining" this package. Even preparing this reply took a comparable effort to the maintenance that I performed in my last PR. For example, I scoured the internet but I could not find an obvious candidate neither in `astropy`, `numpy`, nor in `scipy` for the "mode" or "midpt" statistic. (for `'midpt'` see also https://github.com/spacetelescope/stak-notebooks/issues/83). Some users probably do want this functionality and there is nothing similar to this outside of `IRAF` or `stsci.imagestats`.

----------------

### Performance Analysis

```python
In [1]: # imports:
   ...: import numpy as np
   ...: from stsci.imagestats import ImageStats
   ...: from stsci.imagestats.histogram1d import histogram1d
   ...: 
   ...: # define uniformly and normally distributed data:
   ...: np.random.seed(0)
   ...: d = np.random.random(16000000)
   ...: g = np.random.normal(0.21, 0.3, 16000000)

In [2]: %timeit histogram1d(d, 15, (0.98 - 0.12) / 16, 0.12)
89.4 ms ± 1.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [3]: %timeit np.histogram(d, 15, (0.12, 0.98))
185 ms ± 2.49 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [4]: %timeit ImageStats(g, fields='median', nclip=0)
267 ms ± 3.88 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [5]: %timeit np.median(g)
186 ms ± 1.54 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [6]: st = ImageStats(g, fields='median', nclip=0)

In [7]: print('{}\n{}\n{}\n{}\n{}'.format(st.min, st.max, st.mean, st.stddev, st.median))
-1.4231401681900024
1.8827377557754517
0.20999108254909515
0.2999091148376465
0.21001914143562317
```

Histogram computation with `stsci.imagestats` is about 3x faster than with `numpy.histogram1d`. This affects the speed of computing the `'mode'` and `'midpt'`. The speed of computing the median is 30% slower with  `stsci.imagestats`. However, keep in mind that `ImageStats` always computes the number of points after clipping iterations `npix` (this is very important sometimes!), `min`, `max`, `mean`, and `stddev` (as shown above). Sometimes none of these quantities is not necessary but often they are needed when processing image data. When user wants only the `mean`, obviously user should use `numpy.mean()` for that purpose: using `ImageStats` would be an overkill.

-----------

### Performance example (`imagestats` vs `astropy.stats`) for clipping iterations

```python
In [8]: from astropy import stats
In [9]: %timeit ImageStats(g, fields='mean', nclip=5)
412 ms ± 5.32 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
In [10]: %timeit stats.sigma_clipped_stats(g, cenfunc=np.ma.mean)
1.47 s ± 32.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
In [11]: %timeit ImageStats(g, fields='median', nclip=5)
629 ms ± 5.06 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
In [12]: %timeit stats.sigma_clipped_stats(g, cenfunc=np.ma.median)
2.4 s ± 30.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

Here the performance difference is evident (3x-4x). I only note that my `astropy` version used in these benchmarks was `3.1.dev22467`. Possibly something was improved since that version.

---------

### Conclusions

I think it would be ridiculous not to "maintain" this package just for the sake of switching to `astropy` at the cost of losing functionality, crippling software performance, and all of this with significant effort of switching existing code to new functions. It can be done, but I do not see what is to be gained from this move.

**Comment by pllim** [comment]
Thanks for the detailed analysis, @mcara. As discussed offline, IMHO it would be of greater benefit to move any missing functionality here (algorithm wise or performance wise) upstream, say, to Astropy. I also agree that this work won't be trivial and will require some weeks of dedicated work.

**Comment by mcara** [comment]
First, what is involved in "maintaining" this package? How much time did you spend on it? (CC: @jhunkeler ?)

Second, with regard to _"... it would be of greater benefit to move any missing functionality here upstream, say, to Astropy"_. I find this logic mostly backward:

1. This package was developed _because_ its main functionality was missing from most other "standard" packages and it is still mostly missing. It seems like, in your opinion, we should not be developing specialized packages (this is what this is) and all the development should be moved to `Astropy`.

2. Performance is really crucial. In clipping iterations `imagestats` has a 1s-2s advantage per 4000x4000 image. When sky _matching_ 100 images, this turns into 2-3 hours advantage. I do not see how a "general purpose" `astropy.stats` package could match performance of a specialized package.

**Comment by eteq** [comment]
I agree with @pllim here.  

> what is involved in "maintaining" this package?

There's a hidden cost in all of these "small" packages floating around. Users simply do not find them. When someone leaves the institute or just wants to offload their work to someone else because their priorities have shifted, it's harder to do that if they have been the sole maintainer/expert in a thing.  So the "cost" may not be obvious to any individual, but it's paid by the institute and the community as a whole.

More narrowly, *other* similar packages I've worked with have broken due to subtle changes in compilers. Anything on the C/Python boundary has to be kept up-to-date now and again with architectural changes, etc. Just because it hasn't happened in this one package yet doesn't mean it never will.


>  It seems like, in your opinion, we should not be developing specialized packages (this is what this is) and all the development should be moved to Astropy.

That is correct.  I fully agree with @pllim here.  Writing packages of general functionality that *no one except us uses* is not consistent with the institute's values of service to the scientific community.  It is also a waste of our resources because someone in e.g. INS is surely using a less performant version of this due to not being aware.

> I do not see how a "general purpose" astropy.stats package could match performance of a specialized package

Very trivially: we port this implementation to `astropy.stats`! (Or numpy, or whever it belongs).  That's the whole point: lower the maintainence burden by sharing the load with others who use this sort of functionality.


The real question is what the cost is.  If it's really, say, months of effort, we should put migrating this package on the backlog of "nice to haves", but it's probably not a super high priority.

**Comment by mcara** [comment]
I disagree with almost everything. I do not buy the argument about hidden cost: you can't provide evidence of how much effort was put to maintain this package. Second, I do not see how the existence of this package is not consistent with institute's values: the end product for the users are processing pipelines, drizzlepac, axe (?), acs_destripe, etc. Are you implying that having specialized packages that are shared among institute's other software is against institute values?

**Comment by mcara** [comment]
Just dropping this package into `astropy.stats` "as is" and then modifying our software to witch to the new import should be trivial. But I doubt this is the right way to proceed (personally, i.e., I do not like `ImageStats`'s API).

**Comment by hcferguson** [comment]
For me it falls into two buckets -- "nice to haves" for Astropy to improve performance and "should be retired at some point, rather than left unmaintained" to reduce our overall load on maintenance. If poor performance in Astropy is a problem for us, it is a problem for others as well.  And the lack of documentation is a problem even for people internally. 

The same performance problem seems to have motivated Tom Robitaille's [fast-histogram](https://github.com/astrofrog/fast-histogram) package, which is also something of an orphan, albeit a very young one. It would be interesting to compare performance. Seems to me that if these things become a dependency for Astropy higher-level functions, then they should go in Astropy core eventually. Better still, scipy, but that may be harder to navigate.

**Comment by mcara** [comment]
Alright, I don't disagree with the boss 😄 ... BUT...

What kind of "load on maintenance" are we talking about in relation to this package? I bet that before my PR none of the participants in this discussion did think that "we must do something about this `imagestats`: it is draining our resources". The small maintenance cost is simply shared by the rest of the packages. 

From Tom's README for his fast-histogram package:

> ### Why not contribute this to Numpy directly?
> As mentioned above, the Numpy functions are much more versatile, so they could not be replaced by the ones here. One option would be to check in Numpy's functions for cases that are simple and dispatch to functions such as the ones here, or add dedicated functions for regular binning. I hope we can get this in Numpy in some form or another eventually, but for now, the aim is to have this available to packages that need to support a range of Numpy versions.

I think this is a healthy approach. We need this package for now; let's see if we can improve `astropy`, etc.; switch later. I am not fundamentally against using performant algorithms from _other_ packages. I just do not think we are ready to switch _now_ and "retire" `imagestats` (or be getting ready to do it "soon") just because `histogram1d` can be replaced with a `numpy` version.

**Comment by pllim** [comment]
Indeed, I wasn't saying that you need to stop using this right now. I apologize if I gave that impression in the original issue comment. This is more for long term planning. :grimacing:

**Comment by mcara** [comment]
> Seems ridiculous that we have to maintain this entire namespace package with only 1 function.

... sounded pretty dramatic to me. 😄

**Comment by pllim** [comment]
It is still "ridiculous" but it does not imply we have to be un-ridiculous in the next minute. Also that was clearly my personal opinion and you are free to disagree with it. :wink:

**Comment by eteq** [comment]
> I disagree with almost everything. 

Admittedly, so do I but I am trying to break myself of that habit 😜 

>  We need this package for now; let's see if we can improve astropy, etc.; switch later. 

Yep, with you there.  I agree with @pllim that this isn't *urgent*, but it's also a thing we want to try to do in general rather than having a myriad of specialized packages that are never passed upstream.  

Put another way: I see this issue as a "that's the goal" rather than "this is urgent to do right now".   Notably, the fact that this is its own repo means it's a lot harder to sort/prioritize issues like this... which is precisely one of my points!

>  "we must do something about this imagestats: it is draining our resources"

I don't think that specifically about about `imagestats`, but we *do* spend time thinking about this in a general sense for all of the little packages floating around *like* this one. The point is that no particular *specific* package is an undue burden but collectively they make maintenance, management, and shared know-how harder.

**Comment by pllim** [comment]
Why don't we keep it open for now?

**Comment by mcara** [comment]
Just asking... Keep it open if you want to.

**Comment by SaOgaz** [comment]
For the record @mcara, I've been the one whose spent about a week of my time in total trying to manage these small floating packages (figure out who owns them, what they are for, do we still use them?).  In addition each time we need to do something like, switch all our repos to Python 3.... there's overhead.

**Comment by SaOgaz** [comment]
Hi all,

What's the status on this? If we decide to keep it for now, someone needs to update the help reference and get rid of the python 2, per the two open issues right now.

**Comment by mcara** [comment]
As discussed above, at this moment it is better to keep this open. I'll do the maintenance.

**Comment by pllim** [comment]
Well, I guess this is not happening anytime soon...
